#!perl -w


BEGIN {
	use Carp 'verbose';
	$SIG{ __DIE__ } = \&Carp::confess;
	#use Devel::Confess  qw/color/;
	use Cwd qw/cwd/;
	use Data::Dumper;
}

our ($framework, $ini);
use File::Basename qw/dirname/;
use Cwd qw/abs_path/;

chdir dirname($0);
use lib dirname($0)."/lib";

use lib do {
	open my($f), "main.ini" or die "Нет main.ini: $!";
	read $f, $ini, -s $f;
	close $f;
	
	if($ini =~ /^\s*\[rubin\]\s*path\s*=\s*(.*)/) { $framework = abs_path($1); "$framework/lib"; }
	else { dirname($0)."/lib" }
};

use Msg;
use Utils;

$ini = Utils::parse_ini(undef, $ini);
if($ini->{"mysql"}{"DNS"}) { require Connect; }

@ARGV = "qq" unless @ARGV;
my $path = "bin/$ARGV[0].pl";
my $ret;
if(-e $path) { require $path; }
elsif($framework && -e "$framework/$path") { require "$framework/$path"; }
else { die "Команда `$path` не найдена" }

1;