
requires 'common::sense';
requires 'Data::Dumper::AutoEncode';
requires 'Coro';
requires 'Coro::AIO';
requires 'IO::AIO';
requires 'AnyEvent::AIO';
requires 'Text::Glob';

#requires 'HTML::Entities';
